# minio-tenant-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-prod-tenant
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ALMGHAS/MinIO_Operator_OnEKS_Argocd.git
    targetRevision: main
    path: minio/tenant
    helm:
      valueFiles:
        - minio-prod-tenant-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: minio-prod

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
