apiVersion: v1
kind: Service
metadata:
  name: minio-operator-console-lb
  namespace: minio-operator
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4221
  selector:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
    operator: leader
